input:
    input.go: |
        package structs

        // goverter:converter
        type Converter interface {
            // goverter:ignore Age
            Convert(source Input) (*Output)

            ConvertSub(source Input) (Output)
        }

        type Input struct {
            Name string
        }
        type Output struct {
            Name string
        }
error: |-
    Overlapping field mapping found.

    Please move the field related goverter:* comments from this method:
        func (github.com/rahimlis/go-converter/execution.Converter).Convert(source github.com/rahimlis/go-converter/execution.Input) *github.com/rahimlis/go-converter/execution.Output

    to this method:
        func (github.com/rahimlis/go-converter/execution.Converter).ConvertSub(source github.com/rahimlis/go-converter/execution.Input) github.com/rahimlis/go-converter/execution.Output

    Goverter will use ConvertSub inside the implementation of Convert, thus, field related settings would be ignored.
