name: build
on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/setup-go@v3
                with:
                    go-version: 1.20.x
            -   uses: actions/checkout@v3
            -   uses: golangci/golangci-lint-action@v3
                with:
                    version: v1.51.1
            -   run: go build ./cmd/goverter
            -   run: go test -coverpkg ./...  -coverprofile=coverage.txt -covermode=atomic ./...
            -   run: bash <(curl -s https://codecov.io/bash)
    'build_go116':
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/setup-go@v3
                with:
                    go-version: 1.16.x
            -   uses: actions/checkout@v3
            -   run: go build ./cmd/goverter
